### ISSUE TITLE
Error when running tableRuns function

### ISSUE THREAD

**Issue by alanaselli** [bioinformatics-ptp/detectRUNS#35]
**Describe the bug**
The function works fine on the example data, however when I try using it with my own data (and in more than one situation) I get the following error:

```Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length```

**To Reproduce**
```
library(detectRUNS)

ped = 'scenario_14.ped'
map = 'scenario_14.map'

# Sliding windows approach

slidingRuns = slidingRUNS.run(
    genotypeFile = ped,
    mapFile = map,
    windowSize = 15,
    threshold = 0.05,
    minSNP = 20,
    maxOppWindow = 1, 
    maxMissWindow = 1,
    maxGap = 10^6, 
    minLengthBps = 1000000, 
    minDensity = 1/10^3, # SNP/kbps
)

topRuns <- tableRuns(
    runs =  slidingRuns, genotypeFile = ped, mapFile = map, 
    threshold = 0.7)
```

In the example above I used simulated cattle data, however I've had the same problem when using real cattle and sheep data provided from the [WIDDE database](http://widde.toulouse.inra.fr). All other functions work fine with my data.

**detectRUNS version**
```
> packageVersion("detectRUNS")
[1] ‘0.9.6’
```

**platform**
```
> R.version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.0                         
year           2022                        
month          04                          
day            22                          
svn rev        82229                       
language       R                           
version.string R version 4.2.0 (2022-04-22)
nickname       Vigorous Calisthenics       
```

Thanks in advance.

**Comment by malbianco** [comment]
Hi Alana. 
I don't know which dataset you used but if you can provide me with the direct link I will try to run it on my computer.
however, last week I had a similar problem. what I did was reprocess the ped/map file using plink and re-run all analyses in R. 
Another factor that can generate the error is if you have special characters on your data like '/' or other. In that case, I suggest removing them or renaming the names.

Gabriele

**Comment by alanaselli** [comment]
Gabriele, thank you for the quick reply.

Here is a very similar data to the one that I used in the example.

[scenario_05.map.txt](https://github.com/bioinformatics-ptp/detectRUNS/files/9870621/scenario_05.map.txt)
[scenario_05.ped.txt](https://github.com/bioinformatics-ptp/detectRUNS/files/9870622/scenario_05.ped.txt)

**Comment by malbianco** [comment]
Alana,
everything works properly using the parameters you give in the beginning. You load 'scenario_14", but you gave me the link for 'scenario_05'. 
I also noticed that the animal ID in the ped file is a number. I don't know if this may affect your pipeline, but you can convert the ID into a character by adding ID_ before each ID. This was how I solve one of my problems last week.

Gabriele

**Comment by alanaselli** [comment]
I rerun the script with the scenario_05 files, and it worked. Turns out the percentage (0.7) was too high for one data set, but not for the other. I had the same problem with other data sets, so I figured it was a function error, although it's not. Maybe you could change the error description, so the user knows that they should adjust the threshold?

Obs.: it works fine even with numeric IDs.

Thank you very much for you attention, it helped me realize what I was doing wrong!
