### ISSUE TITLE
Get version 0.9.7 

### ISSUE THREAD

**Issue by biojiangke** [bioinformatics-ptp/detectRUNS#43]
**Is your feature request related to a problem? Please describe.**
I'd like to get the additional frequency information from tableRun function implemented in version 0.9.7.

**Describe the solution you'd like**
Since CRAN is only pushing version 0.9.6 through install.packages(), how do I install the newer version?

**Describe alternatives you've considered**
I'm searching ways to install through source code and GitHub directly, but have not tried.

**Additional context**
Could the authors suggest a good way to install the newest version 0.9.7, with some detailed instructions? I'd like to avoid breaking the current installation because it is used in a production environment.

**Comment by bunop** [comment]
dear @biojiangke ,

unfortunately *detectRUNs 0.9.7* is not yet ready to be published on CRAN. If you need to test the latest version, you may install this package using `devtools`, for example:

```R
library("devtools")
install_github("bioinformatics-ptp/detectRUNS", subdir="detectRUNS", ref="devel") 
```

Where the `ref` parameter stands for the branch of the repository you want to install. 

Hope this helps

**Comment by biojiangke** [comment]
Thank you for your help! I'll give this a try!
